function addLog(id,msg,cls){const l=document.getElementById(id);const d=document.createElement('div');d.className=cls||'le';d.textContent=msg;l.appendChild(d);l.scrollTop=l.scrollHeight}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function setConf(fillId,pctId,n,cheatProb){const c=(1-Math.pow(cheatProb,n))*100;document.getElementById(fillId).style.width=Math.min(c,100)+'%';document.getElementById(pctId).textContent=c.toFixed(2)+'%'}

let caveState={n:0,running:false,auto:false};let cavePos={x:100,y:20};
function caveSetControls(){const locked=caveState.running||caveState.auto;document.getElementById('cave-btn').disabled=locked;document.getElementById('cave-auto-btn').disabled=locked;document.getElementById('cave-reset-btn').disabled=locked;document.getElementById('bluff-tog').disabled=locked}
function caveAnim(toX,toY,ms){return new Promise(res=>{const g=document.getElementById('cave-prover-g');const from={...cavePos};const start=performance.now();function tick(now){const t=Math.min((now-start)/ms,1);const e=t<.5?2*t*t:-1+(4-2*t)*t;const x=from.x+(toX-from.x)*e;const y=from.y+(toY-from.y)*e;g.setAttribute('transform',`translate(${x},${y})`);if(t<1)requestAnimationFrame(tick);else{cavePos={x:toX,y:toY};res()}}requestAnimationFrame(tick)})}
function setProverColor(col){document.querySelector('#cave-prover-g circle').setAttribute('fill',col)}
async function caveRound(){if(caveState.running||caveState.auto)return;caveState.running=true;caveSetControls();try{const bluffing=document.getElementById('bluff-tog').checked;const wentLeft=Math.random()<.5;setProverColor('#4f7bff');document.getElementById('cave-challenge').textContent='';document.getElementById('cave-status').textContent='Prover enters cave…';await caveAnim(100,20,400);await caveAnim(100,85,500);document.getElementById('cave-status').textContent='Prover reaches fork — goes '+(wentLeft?'LEFT':'RIGHT')+' (unseen by verifier)';await caveAnim(wentLeft?58:142,170,500);await sleep(500);const challengeLeft=Math.random()<.5;document.getElementById('cave-challenge').textContent='→ CHALLENGE: "Come out the '+(challengeLeft?'LEFT':'RIGHT')+' side!"';await sleep(400);const success=bluffing?(wentLeft===challengeLeft):true;if(success){const tx=challengeLeft?58:142;await caveAnim(tx,170,400);setProverColor('#34d399');document.getElementById('cave-status').textContent='✓ Exited correct side';caveState.n++;addLog('cave-log','R'+caveState.n+': challenge='+(challengeLeft?'L':'R')+(bluffing?' [BLUFF]':'')+' → ✓ PASS','lok');setConf('cave-fill','cave-pct',caveState.n,.5);document.getElementById('cave-n').textContent=caveState.n;document.getElementById('cave-cp').textContent=(Math.pow(.5,caveState.n)*100).toFixed(4)+'%'}else{setProverColor('#f87171');document.getElementById('cave-status').textContent='✗ Wrong exit — CAUGHT bluffing!';addLog('cave-log','R'+(caveState.n+1)+': challenge='+(challengeLeft?'L':'R')+' [BLUFF] → ✗ CAUGHT','lerr')}await sleep(700);setProverColor('#4f7bff');await caveAnim(100,20,500)}finally{caveState.running=false;caveSetControls()}}
async function caveAuto(){if(caveState.running||caveState.auto)return;caveState.auto=true;caveSetControls();try{for(let i=0;i<10;i++){caveState.running=true;caveSetControls();try{const bluffing=document.getElementById('bluff-tog').checked;const wentLeft=Math.random()<.5;setProverColor('#4f7bff');document.getElementById('cave-challenge').textContent='';document.getElementById('cave-status').textContent='Prover enters cave…';await caveAnim(100,20,400);await caveAnim(100,85,500);document.getElementById('cave-status').textContent='Prover reaches fork — goes '+(wentLeft?'LEFT':'RIGHT')+' (unseen by verifier)';await caveAnim(wentLeft?58:142,170,500);await sleep(500);const challengeLeft=Math.random()<.5;document.getElementById('cave-challenge').textContent='→ CHALLENGE: "Come out the '+(challengeLeft?'LEFT':'RIGHT')+' side!"';await sleep(400);const success=bluffing?(wentLeft===challengeLeft):true;if(success){const tx=challengeLeft?58:142;await caveAnim(tx,170,400);setProverColor('#34d399');document.getElementById('cave-status').textContent='✓ Exited correct side';caveState.n++;addLog('cave-log','R'+caveState.n+': challenge='+(challengeLeft?'L':'R')+(bluffing?' [BLUFF]':'')+' → ✓ PASS','lok');setConf('cave-fill','cave-pct',caveState.n,.5);document.getElementById('cave-n').textContent=caveState.n;document.getElementById('cave-cp').textContent=(Math.pow(.5,caveState.n)*100).toFixed(4)+'%'}else{setProverColor('#f87171');document.getElementById('cave-status').textContent='✗ Wrong exit — CAUGHT bluffing!';addLog('cave-log','R'+(caveState.n+1)+': challenge='+(challengeLeft?'L':'R')+' [BLUFF] → ✗ CAUGHT','lerr')}await sleep(700);setProverColor('#4f7bff');await caveAnim(100,20,500)}finally{caveState.running=false;caveSetControls()}await sleep(100)}}finally{caveState.auto=false;caveSetControls()}}
function caveReset(){if(caveState.running||caveState.auto)return;caveState={n:0,running:false,auto:false};cavePos={x:100,y:20};document.getElementById('cave-prover-g').setAttribute('transform','translate(100,20)');setProverColor('#4f7bff');document.getElementById('cave-status').textContent='Ready.';document.getElementById('cave-challenge').textContent='';document.getElementById('cave-fill').style.width='0%';document.getElementById('cave-pct').textContent='0.00%';document.getElementById('cave-n').textContent='0';document.getElementById('cave-cp').textContent='100%';document.getElementById('cave-log').innerHTML='<span class="le">— protocol log —</span>';caveSetControls()}
