function addLog(id,msg,cls){const l=document.getElementById(id);const d=document.createElement('div');d.className=cls||'le';d.textContent=msg;l.appendChild(d);l.scrollTop=l.scrollHeight}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function rInt(a,b){const arr=new Uint32Array(1);crypto.getRandomValues(arr);return a+(arr[0]%(b-a+1))}
function rHex(bytes){const arr=new Uint8Array(bytes);crypto.getRandomValues(arr);return Array.from(arr).map(b=>b.toString(16).padStart(2,'0')).join('')}
function setConf(fillId,pctId,n,cheatProb){const c=(1-Math.pow(cheatProb,n))*100;document.getElementById(fillId).style.width=Math.min(c,100)+'%';document.getElementById(pctId).textContent=c.toFixed(2)+'%'}

const TRUTH=['A','B','C','B','C'];const EDGES=[[0,1],[1,2],[2,3],[3,4],[4,0],[0,2]];const EIDS=['e01','e12','e23','e34','e40','e02'];const COLORS={A:{fill:'#4a1515',stroke:'#ef4444',label:'RED'},B:{fill:'#0f2456',stroke:'#3b82f6',label:'BLUE'},C:{fill:'#0d3320',stroke:'#22c55e',label:'GRN'}};
let gState={n:0,phase:'idle',perm:null,commits:null,busy:false,auto:false};
function graphSetControls(){const busy=gState.busy||gState.auto;document.getElementById('g-btn-r').disabled=busy||gState.phase==='committed';document.getElementById('g-btn-c').disabled=busy||gState.phase!=='committed';document.getElementById('g-btn-a').disabled=busy;document.getElementById('g-btn-x').disabled=busy}
function graphResetViz(){for(let i=0;i<5;i++){document.getElementById('n'+i).setAttribute('fill','#131c2e');document.getElementById('n'+i).setAttribute('stroke','#1c2540');const l=document.getElementById('l'+i);l.setAttribute('fill','#3a4a68');l.textContent='0x…'}EIDS.forEach(id=>{document.getElementById(id).setAttribute('stroke','#1c2540');document.getElementById(id).setAttribute('stroke-width','2')})}
function simCommit(color,nonce){return btoa(color+'|'+nonce).substring(0,8)+'…'}
function shuffleColors(){const perm=['A','B','C'];for(let i=perm.length-1;i>0;i--){const j=rInt(0,i);const tmp=perm[i];perm[i]=perm[j];perm[j]=tmp}return perm}
function renderCommitTable(){if(!gState.commits)return;const tbody=document.getElementById('g-commit-table');tbody.innerHTML='';for(let i=0;i<5;i++){const tr=document.createElement('tr');const tdN=document.createElement('td');const tdH=document.createElement('td');tdN.textContent=String(i);tdH.textContent=gState.commits[i].hash;tr.appendChild(tdN);tr.appendChild(tdH);tbody.appendChild(tr)}}
function graphRound(){if(gState.busy||gState.auto||gState.phase==='committed')return;gState.phase='committed';const perm=shuffleColors();gState.perm=perm;gState.commits=TRUTH.map((c,i)=>{const nc=perm['ABC'.indexOf(c)];const nonce=rHex(4);return{color:nc,nonce,hash:simCommit(nc,nonce)}});graphResetViz();for(let i=0;i<5;i++){document.getElementById('l'+i).textContent=gState.commits[i].hash}renderCommitTable();document.getElementById('g-round-info').textContent='Round '+(gState.n+1)+': prover re-colored and committed. Hashes published.';document.getElementById('g-challenge').textContent='';graphSetControls()}
function graphChallenge(){if(gState.busy||gState.auto||gState.phase!=='committed')return;gState.phase='revealed';const ei=rInt(0,5);const[a,b]=EDGES[ei];document.getElementById('g-challenge').textContent='→ CHALLENGE: reveal edge '+a+'–'+b;document.getElementById(EIDS[ei]).setAttribute('stroke','#fbbf24');document.getElementById(EIDS[ei]).setAttribute('stroke-width','3');[a,b].forEach(ni=>{const cm=gState.commits[ni];const cd=COLORS[cm.color];document.getElementById('n'+ni).setAttribute('fill',cd.fill);document.getElementById('n'+ni).setAttribute('stroke',cd.stroke);const l=document.getElementById('l'+ni);l.setAttribute('fill',cd.stroke);l.textContent=cd.label});const ok=gState.commits[a].color!==gState.commits[b].color;gState.n++;if(ok){addLog('g-log','R'+gState.n+': edge '+a+'–'+b+' → '+COLORS[gState.commits[a].color].label+' ≠ '+COLORS[gState.commits[b].color].label+' ✓','lok')}else{addLog('g-log','R'+gState.n+': FAIL — same color ✗','lerr')}setConf('g-fill','g-pct',gState.n,5/6);document.getElementById('g-n').textContent=gState.n;document.getElementById('g-cp').textContent=(Math.pow(5/6,gState.n)*100).toFixed(2)+'%';graphSetControls()}
async function graphAuto(){if(gState.busy||gState.auto)return;gState.auto=true;graphSetControls();try{for(let i=0;i<10;i++){graphRound();await sleep(300);graphChallenge();await sleep(300)}}finally{gState.auto=false;graphSetControls()}}
function graphReset(){if(gState.busy||gState.auto)return;gState={n:0,phase:'idle',perm:null,commits:null,busy:false,auto:false};graphResetViz();document.getElementById('g-round-info').textContent='Press "New Round" to commit.';document.getElementById('g-challenge').textContent='';document.getElementById('g-fill').style.width='0%';document.getElementById('g-pct').textContent='0.00%';document.getElementById('g-n').textContent='0';document.getElementById('g-cp').textContent='100%';document.getElementById('g-log').innerHTML='<span class="le">— protocol log —</span>';document.getElementById('g-commit-table').innerHTML='<tr><td>0</td><td>0x…</td></tr><tr><td>1</td><td>0x…</td></tr><tr><td>2</td><td>0x…</td></tr><tr><td>3</td><td>0x…</td></tr><tr><td>4</td><td>0x…</td></tr>';graphSetControls()}
