function addLog(id,msg,cls){const l=document.getElementById(id);const d=document.createElement('div');d.className=cls||'le';d.textContent=msg;l.appendChild(d);l.scrollTop=l.scrollHeight}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function rInt(a,b){const arr=new Uint32Array(1);crypto.getRandomValues(arr);return a+(arr[0]%(b-a+1))}
function modpow(base,exp,mod){let r=1n,b=BigInt(base)%BigInt(mod),e=BigInt(exp),m=BigInt(mod);while(e>0n){if(e&1n)r=r*b%m;e>>=1n;b=b*b%m}return Number(r)}
function setConf(fillId,pctId,n,cheatProb){const c=(1-Math.pow(cheatProb,n))*100;document.getElementById(fillId).style.width=Math.min(c,100)+'%';document.getElementById(pctId).textContent=c.toFixed(2)+'%'}

let schnorrN=0;let schnorrBusy=false;
function schnorrSetControls(){document.getElementById('s-btn').disabled=schnorrBusy;document.getElementById('s-cheat-btn').disabled=schnorrBusy;document.getElementById('s-reset-btn').disabled=schnorrBusy}
async function schnorrRun(cheat){if(schnorrBusy)return;schnorrBusy=true;schnorrSetControls();try{['s2','s3','s4'].forEach(id=>document.getElementById(id).style.opacity='.3');document.getElementById('s-result').textContent='';const r=rInt(1,2051);const R=modpow(5,r,2053);document.getElementById('s-r').textContent=r;document.getElementById('s-r2').textContent=r;document.getElementById('s-R').textContent=R;document.getElementById('s-r3').textContent=r;await sleep(350);const c=rInt(1,50);document.getElementById('s-c').textContent=c;document.getElementById('s-c2').textContent=c;document.getElementById('s2').style.opacity='1';await sleep(350);let s;if(cheat){s=rInt(1,2051)}else{s=((r+c*17)%2052+2052)%2052}document.getElementById('s-s').textContent=s;document.getElementById('s3').style.opacity='1';await sleep(350);const lhs=modpow(5,s,2053);const yc=modpow(375,c,2053);const rhs=(yc*R)%2053;const ok=lhs===rhs;document.getElementById('s-lhs').textContent=lhs;document.getElementById('s-rhs').textContent=rhs;document.getElementById('s4').style.opacity='1';const res=document.getElementById('s-result');if(ok){res.innerHTML='<span style="color:var(--ok)">✓ VERIFIED — values match</span>';if(!cheat){schnorrN++;setConf('s-fill','s-pct',schnorrN,1/50)}addLog('s-log','g^'+s+' mod p = '+lhs+' = R·y^c ✓','lok')}else{res.innerHTML='<span style="color:var(--err)">✗ FAILED — '+lhs+' ≠ '+rhs+'</span>';addLog('s-log','CHEAT: g^s='+lhs+' ≠ R·y^c='+rhs+' → CAUGHT','lerr')}}finally{schnorrBusy=false;schnorrSetControls()}}
function schnorrReset(){if(schnorrBusy)return;schnorrN=0;['s-r','s-r2','s-R','s-r3','s-c','s-c2','s-s','s-lhs','s-rhs'].forEach(id=>{const el=document.getElementById(id);if(el)el.textContent='?'});document.getElementById('s-result').textContent='';['s2','s3','s4'].forEach(id=>document.getElementById(id).style.opacity='.3');document.getElementById('s-fill').style.width='0%';document.getElementById('s-pct').textContent='0.00%';document.getElementById('s-log').innerHTML='<span class="le">— protocol log —</span>';schnorrSetControls()}
